ptm2 <- proc.time()
setwd("/home/oscar/Documents/Capstone")
con <- file("./en_US/en_US.blogs.txt", "r") ## Creates the connection to a file
library(tm)
corpus1 <- VCorpus(VectorSource(readLines(con, 1000)))
close(con)
library (openNLP)
library (tm)
library (qdap)
library(RWeka)
corpus1 <- tm_map(corpus1, removeNumbers)
corpus1 <- tm_map(corpus1, stripWhitespace)
corpus1 <- tm_map(corpus1, tolower)
corpus1 <- tm_map(corpus1, removePunctuation)
corpus1 <- tm_map(corpus1, removeWords, stopwords("english"))
corpus1 <- tm_map(corpus1, PlainTextDocument)
cleanCorpus1 <- data.frame(text=unlist(sapply(corpus1, `[`, "content")), stringsAsFactors=F)